[versions]
agp = "8.4.0"

[libraries]

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
rust-android = { id = "org.mozilla.rust-android-gradle.rust-android", version = "0.9.4" }

